USE [master]
GO

/****** Object:  Database [DemoUser]    Script Date: 2/16/2022 1:25:57 PM ******/
CREATE DATABASE [DemoUser]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DemoUser', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\DemoUser.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DemoUser_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\DemoUser_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DemoUser].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DemoUser] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DemoUser] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DemoUser] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DemoUser] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DemoUser] SET ARITHABORT OFF 
GO

ALTER DATABASE [DemoUser] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DemoUser] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DemoUser] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DemoUser] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DemoUser] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DemoUser] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DemoUser] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DemoUser] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DemoUser] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DemoUser] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DemoUser] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DemoUser] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DemoUser] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DemoUser] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DemoUser] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DemoUser] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DemoUser] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DemoUser] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [DemoUser] SET  MULTI_USER 
GO

ALTER DATABASE [DemoUser] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DemoUser] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DemoUser] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DemoUser] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [DemoUser] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DemoUser] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [DemoUser] SET QUERY_STORE = OFF
GO

ALTER DATABASE [DemoUser] SET  READ_WRITE 
GO

